/**
 * @zh 节点编辑器 CSS 样式文本
 * @en Node Editor CSS style text
 *
 * @zh 此文件在构建时由 vite 插件自动生成
 * @en This file is auto-generated by vite plugin during build
 */

// Placeholder - will be replaced by vite plugin during build
export const nodeEditorCssText = '__NODE_EDITOR_CSS_PLACEHOLDER__';

/**
 * @zh 将 CSS 注入到指定的根节点（支持 Shadow DOM）
 * @en Inject CSS into specified root node (supports Shadow DOM)
 *
 * @param root - @zh 目标根节点（Document 或 ShadowRoot）@en Target root node (Document or ShadowRoot)
 * @param styleId - @zh 样式标签的 ID @en ID for the style tag
 * @returns @zh 创建的 style 元素 @en The created style element
 *
 * @example
 * ```typescript
 * // Inject into Shadow DOM
 * const shadowRoot = element.attachShadow({ mode: 'open' });
 * injectNodeEditorStyles(shadowRoot);
 *
 * // Inject into document (with custom ID)
 * injectNodeEditorStyles(document, 'my-editor-styles');
 * ```
 */
export function injectNodeEditorStyles(
    root: Document | ShadowRoot | DocumentFragment,
    styleId: string = 'esengine-node-editor-styles'
): HTMLStyleElement | null {
    // Check if already injected
    const existingStyle = (root as any).getElementById?.(styleId) ||
        (root as any).querySelector?.(`#${styleId}`);
    if (existingStyle) {
        return existingStyle as HTMLStyleElement;
    }

    // Create and inject style element
    const style = document.createElement('style');
    style.id = styleId;
    style.textContent = nodeEditorCssText;

    if ('head' in root) {
        // Document
        (root as Document).head.appendChild(style);
    } else {
        // ShadowRoot or DocumentFragment
        root.appendChild(style);
    }

    return style;
}
