import EventEmitter from 'events';
import { AssetManagerEvents } from '../@types/private';
import assetQuery from './query';
import assetOperation from './operation';
import assetHandlerManager from './asset-handler';
export interface TypedAssetManager extends EventEmitter {
    on<K extends keyof AssetManagerEvents>(event: K, listener: AssetManagerEvents[K]): this;
    once<K extends keyof AssetManagerEvents>(event: K, listener: AssetManagerEvents[K]): this;
    emit<K extends keyof AssetManagerEvents>(event: K, ...args: Parameters<AssetManagerEvents[K]>): boolean;
    removeListener<K extends keyof AssetManagerEvents>(event: K, listener: AssetManagerEvents[K]): this;
    removeAllListeners<K extends keyof AssetManagerEvents>(event?: K): this;
    listeners<K extends keyof AssetManagerEvents>(event: K): Function[];
    listenerCount<K extends keyof AssetManagerEvents>(event: K): number;
    queryAssets: typeof assetQuery.queryAssets;
    queryAssetDependencies: typeof assetQuery.queryAssetDependencies;
    queryAssetUsers: typeof assetQuery.queryAssetUsers;
    queryAsset: typeof assetQuery.queryAsset;
    queryAssetInfo: typeof assetQuery.queryAssetInfo;
    queryAssetInfoByUUID: typeof assetQuery.queryAssetInfoByUUID;
    queryAssetInfos: typeof assetQuery.queryAssetInfos;
    querySortedPlugins: typeof assetQuery.querySortedPlugins;
    queryUUID: typeof assetQuery.queryUUID;
    queryPath: typeof assetQuery.queryPath;
    queryUrl: typeof assetQuery.queryUrl;
    generateAvailableURL: typeof assetQuery.generateAvailableURL;
    queryDBAssetInfo: typeof assetQuery.queryDBAssetInfo;
    encodeAsset: typeof assetQuery.encodeAsset;
    queryAssetProperty: typeof assetQuery.queryAssetProperty;
    queryAssetMeta: typeof assetQuery.queryAssetMeta;
    queryAssetMtime: typeof assetQuery.queryAssetMtime;
    importAsset: typeof assetOperation.importAsset;
    saveAssetMeta: typeof assetOperation.saveAssetMeta;
    saveAsset: typeof assetOperation.saveAsset;
    createAsset: typeof assetOperation.createAsset;
    refreshAsset: typeof assetOperation.refreshAsset;
    reimportAsset: typeof assetOperation.reimportAsset;
    renameAsset: typeof assetOperation.renameAsset;
    removeAsset: typeof assetOperation.removeAsset;
    moveAsset: typeof assetOperation.moveAsset;
    generateExportData: typeof assetOperation.generateExportData;
    outputExportData: typeof assetOperation.outputExportData;
    createAssetByType: typeof assetOperation.createAssetByType;
    updateUserData: typeof assetOperation.updateUserData;
    queryIconConfigMap: typeof assetHandlerManager.queryIconConfigMap;
    queryAssetConfigMap: typeof assetHandlerManager.queryAssetConfigMap;
    updateDefaultUserData: typeof assetHandlerManager.updateDefaultUserData;
    getCreateMap: typeof assetHandlerManager.getCreateMap;
    queryAssetUserDataConfig: typeof assetHandlerManager.queryUserDataConfig;
    getEffectBinPath: typeof assetHandlerManager.getEffectBinPath;
    url2uuid(url: string): string;
    url2path(url: string): string;
    path2url(url: string, dbName?: string): string;
    init(): Promise<void>;
    destroyed(): void;
}
declare const typedAssetManager: TypedAssetManager;
export default typedAssetManager;
